apiVersion: v1
kind: Service
metadata:
  name: inspection-service
  labels:
    app: inspection-service
spec:
  type: ClusterIP
  selector:
    app: inspection-service
  ports:
    - port: 80
      targetPort: 8201
      protocol: TCP
